In [12]:
import pandas as pd
import numpy as np

In [10]:
#reading csv
df = pd.read_csv("../Treasury_data.csv")

In [14]:
#Transposing dataframe
df = df.T

In [17]:
# setting dates as columns
df.columns = df.iloc[0]
df = df[1:]

In [21]:
df

04/01/21,04/02/21,04/05/21,04/06/21,04/07/21,04/08/21,04/09/21,04/12/21,04/13/21,04/14/21,04/15/21,04/16/21,04/19/21,04/20/21,04/21/21,04/22/21
0.02,0.02,0.03,0.02,0.01,0.02,0.02,0.02,0.03,0.02,0.02,0.02,0.01,0.01,0.0,0.02
0.02.1,0.02,0.02,0.02,0.02,0.02,0.01,0.02,0.02,0.02,0.01,0.02,0.02,0.02,0.02,0.02
0.02.2,0.02,0.03,0.02,0.02,0.01,0.02,0.02,0.03,0.02,0.02,0.02,0.02,0.03,0.03,0.03
0.04,0.04,0.04,0.04,0.04,0.04,0.03,0.04,0.05,0.04,0.04,0.04,0.04,0.04,0.04,0.04
0.06,0.07,0.06,0.06,0.06,0.05,0.06,0.06,0.06,0.06,0.06,0.06,0.08,0.07,0.07,0.06
0.17,0.19,0.17,0.16,0.16,0.14,0.16,0.18,0.16,0.16,0.16,0.16,0.16,0.15,0.15,0.16
0.35,0.39,0.37,0.35,0.34,0.33,0.35,0.38,0.35,0.35,0.32,0.34,0.34,0.31,0.32,0.32
0.90,0.97,0.94,0.88,0.87,0.85,0.87,0.89,0.85,0.87,0.81,0.84,0.85,0.81,0.81,0.81
1.37,1.42,1.4,1.34,1.34,1.3,1.33,1.35,1.29,1.31,1.24,1.26,1.28,1.25,1.24,1.24
1.69,1.72,1.73,1.67,1.68,1.64,1.67,1.69,1.64,1.64,1.56,1.59,1.61,1.58,1.57,1.57
2.24,2.27,2.28,2.24,2.26,2.22,2.23,2.24,2.21,2.22,2.13,2.15,2.18,2.16,2.16,2.13
2.34,2.35,2.36,2.32,2.35,2.32,2.34,2.34,2.32,2.32,2.23,2.26,2.29,2.27,2.26,2.24